### ISSUE TITLE
`Runes` build fails on Xcode8 beta 6

### ISSUE THREAD

**Issue by gbejarano01** [thoughtbot/Runes#80]
I'm trying to build with Carthage `Argo` from the `master` branch so it's compatible with `Swift 3.0`, and the build fails.

I see that `Argo` declares as a Carthage dependency `Runes` on `master` branch, so if I try to build `Runes` from `master` branch on Xcode8 beta 6, it fails due to some compilation errors.

Is there any way of getting `Argo` and `Runes` to work with `Swift 3.0` I'm not aware of?

Thanks in advance for any help you can provide.

**Comment by jshier** [comment]
There's a [PR](https://github.com/thoughtbot/Runes/pull/79) for the significant beta 6 changes but it hasn't landed yet. You can pull from that branch in the meantime.

**Comment by gfontenot** [comment]
this is fixed now.
